from Backend.database import get_db_connection


def create_tables():
    connection = get_db_connection()

    # Enable pgvector
    connection.execute("""
        CREATE EXTENSION IF NOT EXISTS vector
    """)

    # Users table
    connection.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id SERIAL PRIMARY KEY,
            name VARCHAR(100) NOT NULL,
            email VARCHAR(255) UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)

    # Candidates table
    connection.execute("""
        CREATE TABLE IF NOT EXISTS candidates (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            email TEXT,
            resume_filename TEXT NOT NULL,
            resume_text TEXT NOT NULL,
            embedding VECTOR(768),
            created_at TIMESTAMPTZ DEFAULT NOW()
        )
    """)

    # Jobs table
    connection.execute("""
        CREATE TABLE IF NOT EXISTS jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            title TEXT NOT NULL,
            description TEXT NOT NULL,
            embedding VECTOR(768),
            skills JSONB,
            keywords JSONB,
            created_at TIMESTAMPTZ DEFAULT NOW()
        )
    """)

    # Interview questions table
    connection.execute("""
        CREATE TABLE IF NOT EXISTS interview_questions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
            question TEXT NOT NULL,
            answer TEXT NOT NULL,
            created_at TIMESTAMPTZ DEFAULT NOW()
        )
    """)

    # Vector indexes
    connection.execute("""
        CREATE INDEX IF NOT EXISTS candidates_embedding_idx
        ON candidates
        USING hnsw (embedding vector_cosine_ops)
    """)

    connection.execute("""
        CREATE INDEX IF NOT EXISTS jobs_embedding_idx
        ON jobs
        USING hnsw (embedding vector_cosine_ops)
    """)

    connection.commit()
    connection.close()

    print("Database tables created successfully!")


if __name__ == "__main__":
    create_tables()